export const types = {
    normal: "bg-gray-500",
    fire: "bg-orange-500 text-white",
    water: "bg-blue-500 text-white",
    electric: "bg-yellow-500",
    grass: "bg-green-500",
    ice: "bg-sky-500",
    fighting: "bg-orange-600 text-white",
    poison: "bg-violet-500 text-white",
    ground: "bg-yellow-300-yellow-600",
    flying: "bg-sky-gray",
    psychic: "bg-pink-500 text-white",
    bug: "bg-lime-500 text-white",
    rock: "bg-yellow-600 text-white",
    ghost: "bg-violet-600 text-white",
    dragon: "bg-blue-rose",
    dark: "bg-gray-600 text-white",
    steel: "bg-slate-300",
    fairy: "bg-pink-300",
};
